/** Zusätzlicher Fragenpool (import in trivia-questions.js) */

export const TRIVIA_MORE = [
  { id: 155, cat: "geo", diff: "easy", q: "Hauptstadt von Spanien?", choices: ["Barcelona", "Madrid", "Lissabon", "Sevilla"], a: 1 },
  { id: 156, cat: "geo", diff: "easy", q: "Welches Land liegt nördlich von Deutschland?", choices: ["Schweiz", "Dänemark", "Polen", "Frankreich"], a: 1 },
  { id: 157, cat: "geo", diff: "medium", q: "Welcher Staat ist flächenmäßig der zweitgrößte der Erde?", choices: ["China", "USA", "Kanada", "Brasilien"], a: 2 },
  { id: 158, cat: "geo", diff: "medium", q: "Hauptstadt von Neuseeland?", choices: ["Auckland", "Wellington", "Christchurch", "Queenstown"], a: 1 },
  { id: 159, cat: "geo", diff: "hard", q: "Welcher Berg ist der höchste außerhalb Asiens?", choices: ["Kilimandscharo", "Aconcagua", "Denali", "Mont Blanc"], a: 1 },
  { id: 160, cat: "history", diff: "easy", q: "Wann wurde die DDR gegründet?", choices: ["1933", "1945", "1949", "1961"], a: 2 },
  { id: 161, cat: "history", diff: "easy", q: "Wer war erster Bundeskanzler der BRD?", choices: ["Willy Brandt", "Konrad Adenauer", "Helmut Kohl", "Ludwig Erhard"], a: 1 },
  { id: 162, cat: "history", diff: "medium", q: "Schlacht von Waterloo (Niederlage Napoleons) — Jahr?", choices: ["1805", "1812", "1815", "1848"], a: 2 },
  { id: 163, cat: "history", diff: "medium", q: "Berliner Luftbrücke — ungefähres Jahr?", choices: ["1939", "1948/49", "1956", "1961"], a: 1 },
  { id: 164, cat: "history", diff: "hard", q: "Friede von Westfalen endete grob welchen Krieg?", choices: ["Hundertjähriger Krieg", "Dreißigjähriger Krieg", "Siebenjähriger Krieg", "Erster Weltkrieg"], a: 1 },
  { id: 165, cat: "science", diff: "easy", q: "Wie viele Beine hat eine Spinne typischerweise?", choices: ["6", "8", "10", "12"], a: 1 },
  { id: 166, cat: "science", diff: "easy", q: "Wasser gefriert bei Normaldruck ungefähr bei…", choices: ["0 °C", "100 °C", "−10 °C", "37 °C"], a: 0 },
  { id: 167, cat: "science", diff: "medium", q: "Welches Gas atmen wir primär ein?", choices: ["Reiner Sauerstoff", "Stickstoff-haltige Luft", "Kohlendioxid", "Helium"], a: 1 },
  { id: 168, cat: "science", diff: "medium", q: "DNA-Bausteine (Monomere) heißen…", choices: ["Aminosäuren", "Nukleotide", "Monosaccharide", "Fettsäuren"], a: 1 },
  { id: 169, cat: "science", diff: "hard", q: "Planck-Konstante gehört in welchen Bereich?", choices: ["Klassische Mechanik", "Quantenphysik", "Geometrie", "Thermodynamik nur"], a: 1 },
  { id: 170, cat: "nature", diff: "easy", q: "Welches Tier ist ein Reptil?", choices: ["Wal", "Krokodil", "Fledermaus", "Pinguin"], a: 1 },
  { id: 171, cat: "nature", diff: "easy", q: "Größtes Säugetier der Welt?", choices: ["Elefant", "Blauwal", "Giraffe", "Nashorn"], a: 1 },
  { id: 172, cat: "nature", diff: "medium", q: "Korallen sind grob gesehen…", choices: ["Pflanzen", "Tierkolonien (Polypen)", "Pilze", "Steine"], a: 1 },
  { id: 173, cat: "nature", diff: "medium", q: "Welcher Baum wirft typischerweise im Herbst Laub ab (Laubbaum)?", choices: ["Tanne", "Kiefer", "Eiche", "Fichte"], a: 2 },
  { id: 174, cat: "nature", diff: "hard", q: "Welches Organ filtert Blut und bildet Urin?", choices: ["Leber", "Niere", "Lunge", "Herz"], a: 1 },
  { id: 175, cat: "tech", diff: "easy", q: "Was ist eine „Dateiendung“?", choices: ["Passwort", "Suffix im Dateinamen (z. B. .pdf)", "CPU-Takt", "WLAN-Kanal"], a: 1 },
  { id: 176, cat: "tech", diff: "easy", q: "„WLAN“ steht sinngemäß für…", choices: ["Kabelgebundenes Netz", "Drahtloses lokales Netz", "Weitverkehrsnetz", "Festplatte"], a: 1 },
  { id: 177, cat: "tech", diff: "medium", q: "Was ist ein Compiler grob?", choices: ["Virusscanner", "Übersetzer Quellcode → Maschinencode", "Browser", "Druckertreiber"], a: 1 },
  { id: 178, cat: "tech", diff: "medium", q: "HTTPS nutzt typischerweise TLS für…", choices: ["Komprimierung", "Verschlüsselung/Authentizität", "Nur Bilder", "CPU-Kühlung"], a: 1 },
  { id: 179, cat: "tech", diff: "hard", q: "Was beschreibt das CAP-Theorem grob?", choices: ["Nur Cachegröße", "Kompromiss Konsistenz/Verfügbarkeit/Partition", "Nur UI-Design", "Nur Speicherpreise"], a: 1 },
  { id: 180, cat: "movies", diff: "easy", q: "„E.T.“ — Regisseur?", choices: ["George Lucas", "Steven Spielberg", "James Cameron", "Tim Burton"], a: 1 },
  { id: 181, cat: "movies", diff: "easy", q: "„Frozen“ (Die Eiskönigin): Lied „Let It Go“ — welches Studio (Disney/Pixar)?", choices: ["DreamWorks", "Disney", "Studio Ghibli", "Illumination"], a: 1 },
  { id: 182, cat: "movies", diff: "medium", q: "„Inception“ — Regisseur?", choices: ["Nolan", "Tarantino", "Fincher", "Villeneuve"], a: 0 },
  { id: 183, cat: "movies", diff: "medium", q: "Oscar Bester Film 2004 (US-Verleih)?", choices: ["Finding Nemo", "The Lord of the Rings: Return of the King", "Lost in Translation", "Master and Commander"], a: 1 },
  { id: 184, cat: "movies", diff: "hard", q: "„Metropolis“ (1927) — Land?", choices: ["USA", "Deutschland", "Frankreich", "Sowjetunion"], a: 1 },
  { id: 185, cat: "tv", diff: "easy", q: "„The Office“ (US) spielt vor allem in einem…", choices: ["Krankenhaus", "Büro", "Gefängnis", "Restaurant"], a: 1 },
  { id: 186, cat: "tv", diff: "medium", q: "„Stranger Things“: fiktive Kleinstadt heißt…", choices: ["Riverdale", "Hawkins", "Twin Peaks", "Stars Hollow"], a: 1 },
  { id: 187, cat: "tv", diff: "easy", q: "„South Park“ — Land der Produktion?", choices: ["Japan", "USA", "UK", "Frankreich"], a: 1 },
  { id: 188, cat: "music", diff: "easy", q: "Wie viele Saiten hat eine typische Gitarre?", choices: ["4", "5", "6", "7"], a: 2 },
  { id: 189, cat: "music", diff: "medium", q: "Mozarts vollständiger Name beginnt mit…", choices: ["Ludwig van", "Wolfgang Amadeus", "Johann Sebastian", "Franz Peter"], a: 1 },
  { id: 190, cat: "music", diff: "medium", q: "Welches Genre wird Elvis Presley oft zugeordnet?", choices: ["Punk", "Rock ’n’ Roll", "Techno", "Oper"], a: 1 },
  { id: 191, cat: "music", diff: "hard", q: "„Vier Jahreszeiten“ (Violinkonzerte) — Komponist?", choices: ["Bach", "Vivaldi", "Händel", "Telemann"], a: 1 },
  { id: 192, cat: "literature", diff: "easy", q: "Wer schrieb „Die Verwandlung“?", choices: ["Kafka", "Hesse", "Mann", "Brecht"], a: 0 },
  { id: 193, cat: "literature", diff: "easy", q: "„Sherlock Holmes“ — Autor?", choices: ["Agatha Christie", "Arthur Conan Doyle", "Edgar Allan Poe", "Wilkie Collins"], a: 1 },
  { id: 194, cat: "literature", diff: "medium", q: "„Der Alchimist“ (bekannter Roman) — Autor?", choices: ["Coelho", "Murakami", "Eco", "Pamuk"], a: 0 },
  { id: 195, cat: "literature", diff: "hard", q: "„Die Blechtrommel“ — Autor?", choices: ["Heinrich Böll", "Günter Grass", "Thomas Mann", "Christa Wolf"], a: 1 },
  { id: 196, cat: "culture", diff: "easy", q: "Oktoberfest findet klassischerweise in welcher Stadt statt?", choices: ["Berlin", "München", "Hamburg", "Köln"], a: 1 },
  { id: 197, cat: "culture", diff: "medium", q: "Olympische Sommerspiele 2016 waren in…", choices: ["London", "Rio de Janeiro", "Tokio", "Peking"], a: 1 },
  { id: 198, cat: "art", diff: "easy", q: "„Die Mona Lisa“ hängt im…", choices: ["Uffizien", "Louvre", "Prado", "British Museum"], a: 1 },
  { id: 199, cat: "art", diff: "medium", q: "Bauhaus — welches Jahrhundert/Umfeld?", choices: ["Mittelalter", "20. Jh. Design/Architektur", "Barock", "Antike"], a: 1 },
  { id: 200, cat: "gaming", diff: "easy", q: "Pac-Man frisst primär…", choices: ["Monster", "Punkte/Pills", "Schwerter", "Bananen"], a: 1 },
  { id: 201, cat: "gaming", diff: "medium", q: "Welche Reihe hat den Helden Link?", choices: ["Final Fantasy", "The Legend of Zelda", "Metroid", "Castlevania"], a: 1 },
  { id: 202, cat: "gaming", diff: "hard", q: "Spiel „Tetris“ — ursprünglich entwickelt im…", choices: ["USA", "Sowjetunion/Russland", "Japan", "Finnland"], a: 1 },
  { id: 203, cat: "sport", diff: "easy", q: "Wie viele Ringe hat die Olympische Flagge?", choices: ["4", "5", "6", "7"], a: 1 },
  { id: 204, cat: "sport", diff: "medium", q: "Beim Schwimmen: welcher Stil ist „Kraul“?", choices: ["Brust", "Freistil (crawl)", "Rücken", "Schmetterling"], a: 1 },
  { id: 205, cat: "sport", diff: "medium", q: "WM-Fußball 2006 (Männer) wurde ausgetragen in…", choices: ["Frankreich", "Deutschland", "Japan/Korea", "Südafrika"], a: 1 },
  { id: 206, cat: "food", diff: "easy", q: "Aus welchem Getreide wird klassische italienische Pasta meist gemacht?", choices: ["Reis", "Weizen", "Gerste", "Hirse"], a: 1 },
  { id: 207, cat: "food", diff: "easy", q: "Curry ist oft assoziiert mit Küchen aus…", choices: ["nur Skandinavien", "Südasien u. a.", "nur Peru", "nur Grönland"], a: 1 },
  { id: 208, cat: "food", diff: "medium", q: "Risotto ist ein Gericht basierend auf…", choices: ["Nudeln", "Reis", "Kartoffeln", "Quinoa"], a: 1 },
  { id: 209, cat: "space", diff: "easy", q: "Welcher Planet ist der Sonne am nächsten?", choices: ["Venus", "Merkur", "Erde", "Mars"], a: 1 },
  { id: 210, cat: "space", diff: "medium", q: "Was ist die Milchstraße grob?", choices: ["Ein Asteroid", "Unsere Galaxie", "Ein Mond", "Ein Komet"], a: 1 },
  { id: 211, cat: "mythology", diff: "easy", q: "Wer ist in der griechischen Mythologie Göttin der Weisheit?", choices: ["Aphrodite", "Athena", "Hera", "Artemis"], a: 1 },
  { id: 212, cat: "mythology", diff: "medium", q: "Wer stahl in der Mythologie das Feuer für die Menschen?", choices: ["Odysseus", "Prometheus", "Orpheus", "Perseus"], a: 1 },
  { id: 213, cat: "language", diff: "easy", q: "„Danke“ auf Englisch?", choices: ["Please", "Thank you", "Sorry", "Hello"], a: 1 },
  { id: 214, cat: "language", diff: "medium", q: "Was ist ein „Homonym“ grob?", choices: ["Gegenteil", "gleich klingend/geschrieben, andere Bedeutung", "nur Fremdwort", "nur Dialekt"], a: 1 },
  { id: 215, cat: "politics", diff: "easy", q: "Wer wählt in einer Demokratie typischerweise Regierung/Parlament mit?", choices: ["nur König", "Bürgerinnen und Bürger", "nur Richter", "niemand"], a: 1 },
  { id: 216, cat: "politics", diff: "medium", q: "NATO ist primär eine…", choices: ["Handelsunion", "Militärallianz", "Fußballliga", "Währungsunion"], a: 1 },
  { id: 217, cat: "medicine", diff: "easy", q: "Erste Hilfe: Notruf in Deutschland/EU oft…", choices: ["911", "112", "444", "0800"], a: 1 },
  { id: 218, cat: "medicine", diff: "medium", q: "Antibiotika wirken typischerweise gegen…", choices: ["Viren", "Bakterien (je nach Typ)", "Gebrochene Knochen", "Sonnenbrand"], a: 1 },
  { id: 219, cat: "psychology", diff: "medium", q: "Was misst ein IQ-Test grob (vereinfacht)?", choices: ["Körpergröße", "kognitive Leistung relativ zur Norm", "Musikalität", "Herzfrequenz"], a: 1 },
  { id: 220, cat: "economics", diff: "easy", q: "Was ist ein „Markt“ grob?", choices: ["nur Supermarkt", "Treffen von Angebot und Nachfrage", "nur Staat", "nur Bank"], a: 1 },
  { id: 221, cat: "automotive", diff: "easy", q: "Welche Verkehrsseite gilt in Deutschland?", choices: ["Links", "Rechts", "Wechselnd", "Nur zu Fuß"], a: 1 },
  { id: 222, cat: "geo", diff: "easy", q: "Hauptstadt von Portugal?", choices: ["Porto", "Lissabon", "Madrid", "Barcelona"], a: 1 },
  { id: 223, cat: "geo", diff: "medium", q: "Welcher Ozean liegt zwischen Amerika und Europa?", choices: ["Indischer Ozean", "Atlantik", "Arktis nur", "Rotes Meer"], a: 1 },
  { id: 224, cat: "history", diff: "easy", q: "Mauerfall Berlin (symbolisch) — Jahr?", choices: ["1975", "1989", "1995", "2001"], a: 1 },
  { id: 225, cat: "science", diff: "easy", q: "Wie viele Chromosomenpaare hat ein Mensch typischerweise?", choices: ["21", "23", "46", "48"], a: 1 },
  { id: 226, cat: "nature", diff: "easy", q: "Welches Tier legt Eier und ist ein Vogel?", choices: ["Fledermaus", "Huhn", "Platypus nur", "Wal"], a: 1 },
  { id: 227, cat: "tech", diff: "easy", q: "Was ist ein „Passwort“?", choices: ["Öffentlicher Name", "Geheimes Zeichen zur Authentifizierung", "IP-Adresse", "Drucker"], a: 1 },
  { id: 228, cat: "movies", diff: "easy", q: "„Jurassic Park“ — wovon handelt es grob?", choices: ["Piraten", "Dinos in einem Park", "Weltraum", "Kochen"], a: 1 },
  { id: 229, cat: "sport", diff: "hard", q: "Ironman-Triathlon: typische Reihenfolge?", choices: ["Laufen–Schwimmen–Rad", "Schwimmen–Rad–Laufen", "Rad–Schwimmen–Laufen", "Nur Rad"], a: 1 },
  { id: 230, cat: "culture", diff: "medium", q: "Karneval/Fasching ist stark verbreitet u. a. in…", choices: ["nur Island", "Rheinland und weiteren Regionen", "nur Wüste", "nur Arktis"], a: 1 },
  { id: 231, cat: "science", diff: "medium", q: "Geschwindigkeit ist Weg durch…", choices: ["Masse", "Zeit", "Kraft", "Energie"], a: 1 },
  { id: 232, cat: "literature", diff: "medium", q: "„Der Process“ (Prozess) — Autor?", choices: ["Kafka", "Goethe", "Schiller", "Fontane"], a: 0 },
  { id: 233, cat: "gaming", diff: "easy", q: "In „Tetris“ sind die Teile meist…", choices: ["Kugeln", "fallende Blöcke", "Autos", "Karten"], a: 1 },
  { id: 234, cat: "food", diff: "easy", q: "Was ist Gelato grob?", choices: ["Italienisches Eis", "Suppe", "Brot", "Käsefondue"], a: 0 },
  { id: 235, cat: "space", diff: "hard", q: "Was ist ein „Schwarzes Loch“ grob?", choices: ["leerer Raum", "sehr kompakte Masse mit starker Gravitation", "Stern ohne Licht", "Mond"], a: 1 },
  { id: 236, cat: "mythology", diff: "easy", q: "Wer ist der Hammer tragende Gott in der nordischen Mythologie?", choices: ["Odin", "Thor", "Loki", "Balder"], a: 1 },
  { id: 237, cat: "art", diff: "hard", q: "„Guernica“ — Künstler?", choices: ["Dalí", "Picasso", "Miró", "Goya"], a: 1 },
  { id: 238, cat: "tv", diff: "medium", q: "„The Mandalorian“ gehört zum Universum von…", choices: ["Star Trek", "Star Wars", "Harry Potter", "Marvel nur"], a: 1 },
  { id: 239, cat: "music", diff: "easy", q: "Notenliniensystem hat typischerweise wie viele Linien?", choices: ["3", "4", "5", "6"], a: 2 },
  { id: 240, cat: "geo", diff: "hard", q: "Tote Meer ist bekannt für…", choices: ["Süßwasser", "hohen Salzgehalt", "Eisdecke", "Vulkan aktiv"], a: 1 },
  { id: 241, cat: "history", diff: "medium", q: "Antike: Akropolis steht in…", choices: ["Rom", "Athen", "Kairo", "Bagdad"], a: 1 },
  { id: 242, cat: "nature", diff: "medium", q: "Fotosynthese produziert grob Sauerstoff aus…", choices: ["Stickstoff", "Wasser und CO₂ (vereinfacht)", "reinem Gold", "Methan"], a: 1 },
  { id: 243, cat: "tech", diff: "medium", q: "RAM ist…", choices: ["dauerhafter Speicher ohne Strom", "Arbeitsspeicher (flüchtig)", "nur Grafikkarte", "Netzwerkkabel"], a: 1 },
  { id: 244, cat: "medicine", diff: "easy", q: "Welches Organ pumpt Blut?", choices: ["Lunge", "Herz", "Magen", "Haut"], a: 1 },
  { id: 245, cat: "politics", diff: "hard", q: "Was ist „Checks and balances“ grob?", choices: ["nur Wahl", "Machtteilung/Kontrolle zwischen Ämtern", "Steuern", "Polizeiuniform"], a: 1 },
  { id: 246, cat: "economics", diff: "medium", q: "Angebot steigt, Nachfrage gleich — Preis tendenziell…", choices: ["steigt", "fällt", "ist fix", "wird negativ"], a: 1 },
  { id: 247, cat: "psychology", diff: "easy", q: "Traumdeutung wurde populär u. a. durch…", choices: ["Freud", "Newton", "Darwin", "Curie"], a: 0 },
  { id: 248, cat: "automotive", diff: "medium", q: "Was ist ein Hybridauto grob?", choices: ["nur Diesel", "Kombination Verbrenner/E-Motor o. ä.", "ohne Räder", "nur Flugzeug"], a: 1 },
  { id: 249, cat: "language", diff: "easy", q: "„Hola“ ist typisch…", choices: ["Französisch", "Spanisch", "Russisch", "Arabisch"], a: 1 },
  { id: 250, cat: "movies", diff: "medium", q: "„Avatar“ (2009) spielt grob auf…", choices: ["Mars", "Pandora (fiktiver Mond)", "Titanic", "Erde nur"], a: 1 },
  { id: 251, cat: "sport", diff: "medium", q: "Volleyball-Team hat wie viele Spieler auf dem Feld?", choices: ["5", "6", "7", "11"], a: 1 },
  { id: 252, cat: "food", diff: "medium", q: "Was ist Kimchi typischerweise?", choices: ["italienische Pasta", "fermentiertes Gemüse (koreanisch)", "französische Suppe", "Brot"], a: 1 },
  { id: 253, cat: "science", diff: "hard", q: "Relativitätstheorie ist eng mit welchem Namen verbunden?", choices: ["Newton", "Einstein", "Galilei", "Hawking nur"], a: 1 },
  { id: 254, cat: "culture", diff: "easy", q: "Weihnachten wird in vielen Ländern am…", choices: ["1. Januar", "24./25. Dezember (traditionsabh.)", "31. Oktober", "14. Februar"], a: 1 },
  { id: 255, cat: "literature", diff: "easy", q: "„Emil und die Detektive“ — Autor?", choices: ["Erich Kästner", "Michael Ende", "Astrid Lindgren", "Roald Dahl"], a: 0 },
  { id: 256, cat: "gaming", diff: "medium", q: "„Dark Souls“ ist bekannt für…", choices: ["nur Puzzle ohne Kampf", "herausforderndes Action-RPG", "Rennspiel", "Musikrhythmus"], a: 1 },
  { id: 257, cat: "geo", diff: "medium", q: "Hauptstadt von Kanada?", choices: ["Toronto", "Vancouver", "Ottawa", "Montreal"], a: 2 },
  { id: 258, cat: "history", diff: "hard", q: "Wiener Kongress — Jahrhundert?", choices: ["16.", "19. (1814/15)", "20.", "21."], a: 1 },
  { id: 259, cat: "nature", diff: "hard", q: "Welches Biom hat Permafrost?", choices: ["Regenwald", "Tundra", "Savanne", "Korallenriff"], a: 1 },
  { id: 260, cat: "tech", diff: "easy", q: "„Bug“ in Software bedeutet grob…", choices: ["Feature", "Fehler/Defekt", "Logo", "Lizenz"], a: 1 },
  { id: 261, cat: "art", diff: "medium", q: "Impressionismus — Maler wie Monet assoziiert mit…", choices: ["nur Schwarz-Weiß", "Licht und Farbtupfer", "nur Skulptur", "Pixelkunst"], a: 1 },
  { id: 262, cat: "space", diff: "medium", q: "ISS ist…", choices: ["Interplanetare Sonde", "Internationale Raumstation", "Inselsystem", "Saturnmond"], a: 1 },
  { id: 263, cat: "mythology", diff: "hard", q: "Ikarus flog zu nah an…", choices: ["dem Meer", "der Sonne", "dem Mond", "Vulkan"], a: 1 },
  { id: 264, cat: "tv", diff: "hard", q: "„The Wire“ spielt vor allem in…", choices: ["New York", "Baltimore", "Chicago", "Miami"], a: 1 },
];
